spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071/
  # add colors to the console logging in spring
  output:
    ansi:
      enabled: ALWAYS
  # get services discovery info from eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  # zipkin config with rabbitmq
  zipkin:
    base-url: http://localhost:9411/


#enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

# Configuring info endpoint details
info:
  app:
    name: Gateway Service
    description: Banking Gateway Service App
    version: 1.0.0
