version: "3.8"

services:

  accounts:
    build: .
    ports:
      - "8080:8080"
    networks:
      - banking-app

  loans:
    build: ../loan-service
    ports:
      - "8090:8090"
    networks:
      - banking-app

  cards:
    build: ../card-service
    ports:
      - "9000:9000"
    networks:
      - banking-app

networks:
  banking-app:
