version: "3.8"

services:

  configserver:
    build: ../config-server
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - banking-app

  discovery:
    build: ../discovery-service
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - banking-app
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    build: .
    ports:
      - "8080:8080"
    networks:
      - banking-app
    depends_on:
      - configserver
      - discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    build: ../loan-service
    ports:
      - "8090:8090"
    networks:
      - banking-app
    depends_on:
      - configserver
      - discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    build: ../card-service
    ports:
      - "9000:9000"
    networks:
      - banking-app
    depends_on:
      - configserver
      - discovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  gatewayserver:
    build: ../gateway-service
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - banking-app
    depends_on:
      - configserver
      - discovery
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  banking-app:
