server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PaskoZhelev/banking-microservices-spring-config
          default-label: master
          clone-on-start: true

  # zipkin config with rabbitmq
  zipkin:
    base-url: http://localhost:9411/


  # add colors to the console logging in spring
  output:
    ansi:
      enabled: ALWAYS

encrypt:
  key: QeThVmYq3t6w9z$C