server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  # add colors to the console logging in spring
  output:
    ansi:
      enabled: ALWAYS

encrypt:
  key: QeThVmYq3t6w9z$C