server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  application:
    name: cards
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071/
  # add colors to the console logging in spring
  output:
    ansi:
      enabled: ALWAYS

#enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

# discovery service props
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Configuring info endpoint details
info:
  app:
    name: Cards Microservice
    description: Banking Cards App
    version: 1.0.0

# provide shutdown endpoint on actuator
endpoints:
  shutdown:
    enabled: true
